baseURL = "https://elizabethteas.com"
languageCode = "en"
DefaultContentLanguage = "en"

title = "This Is Me"
#title = "Website of Elizabeth Teas"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

weight = 1
LanguageName = "EN"
contentDir = "content"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true