  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Open Science"
  weight = 200
  identifier = "open science"
  url = "/openscience/"

  [[main]]
  name = "Publications"
  weight = 400
  identifier = "publications"
  url = "/publications/"

  [[main]]
  name = "CV"
  weight = 500
  identifier = "cv"
  url = "/cv/"
