# Edit these
# -----------------------------------------------------------------------
profilePicture = "images/profile-mustache.jpg"
title = "I'm Elizabeth Teas"
description = "I like to run"
author = "Elizabeth Teas"
#copyright = "2021"

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/esohns"

[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/esohns/"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:???@example.com"


# Ignore these
# ------------------------------------------------------------------------
keywords = ""
favicon = "favicons/"
enableMediumZoom = false

# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 

doNotLoadAnimations = false

singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"

# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

#[[socialIcons]]
#icon = "fab fa-github"
#title = "GitHub"
#url = "https://github.com/lxndrblz/anatole/"
